"""Code quality filters for licensed GitHub / documentation shards."""

from __future__ import annotations

import ast
import re
from dataclasses import dataclass

MINIFIED_LINE = 240
LANG_FROM_EXT = {
    ".py": "python",
    ".js": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".jsx": "javascript",
    ".java": "java",
    ".go": "go",
    ".rs": "rust",
    ".c": "c",
    ".h": "c",
    ".cpp": "cpp",
    ".cc": "cpp",
    ".hpp": "cpp",
    ".cs": "csharp",
    ".rb": "ruby",
    ".php": "php",
    ".kt": "kotlin",
    ".swift": "swift",
    ".scala": "scala",
    ".sql": "sql",
    ".sh": "shell",
    ".md": "markdown",
}


@dataclass(frozen=True)
class CodeThresholds:
    min_lines: int = 8
    max_lines: int = 4000
    min_avg_line_len: float = 8.0
    max_avg_line_len: float = 120.0
    max_max_line_len: int = 240
    min_alnum_ratio: float = 0.35
    max_digit_ratio: float = 0.40
    min_comment_ratio: float = 0.0
    max_comment_ratio: float = 0.85
    require_python_parse: bool = True


COMMENT_PREFIX = {
    "python": "#",
    "ruby": "#",
    "shell": "#",
    "rust": "//",
    "go": "//",
    "javascript": "//",
    "typescript": "//",
    "java": "//",
    "c": "//",
    "cpp": "//",
    "csharp": "//",
    "php": "//",
    "kotlin": "//",
    "swift": "//",
    "scala": "//",
}


def infer_language(path: str | None, text: str) -> str:
    if path:
        for ext, lang in LANG_FROM_EXT.items():
            if path.endswith(ext):
                return lang
    if "def " in text and "import " in text:
        return "python"
    if "function " in text and "const " in text:
        return "javascript"
    if "fn " in text and "let " in text and "impl " in text:
        return "rust"
    if "package " in text and "func " in text:
        return "go"
    return "unknown"


def comment_ratio(lines: list[str], language: str) -> float:
    prefix = COMMENT_PREFIX.get(language)
    if not prefix or not lines:
        return 0.0
    comments = sum(1 for ln in lines if ln.lstrip().startswith(prefix))
    return comments / len(lines)


def python_parses(text: str) -> bool:
    try:
        ast.parse(text)
        return True
    except SyntaxError:
        return False


def score_code(text: str, path: str | None = None, thresholds: CodeThresholds | None = None) -> dict:
    cfg = thresholds or CodeThresholds()
    language = infer_language(path, text)
    lines = text.splitlines()
    nonempty = [ln for ln in lines if ln.strip()]
    avg = (sum(len(ln) for ln in nonempty) / max(len(nonempty), 1)) if nonempty else 0.0
    max_len = max((len(ln) for ln in nonempty), default=0)
    alnum = sum(ch.isalnum() for ch in text) / max(len(text), 1)
    digits = sum(ch.isdigit() for ch in text) / max(len(text), 1)
    comments = comment_ratio(nonempty, language)
    generated = bool(
        re.search(r"auto[- ]generated|do not edit|generated by|code generated", text[:800], re.I)
    )
    minified = max_len >= MINIFIED_LINE and avg > 140
    reasons: list[str] = []
    if len(nonempty) < cfg.min_lines or len(nonempty) > cfg.max_lines:
        reasons.append("line_count")
    if not (cfg.min_avg_line_len <= avg <= cfg.max_avg_line_len):
        reasons.append("avg_line_len")
    if max_len > cfg.max_max_line_len:
        reasons.append("max_line_len")
    if alnum < cfg.min_alnum_ratio:
        reasons.append("alnum")
    if digits > cfg.max_digit_ratio:
        reasons.append("digits")
    if comments > cfg.max_comment_ratio:
        reasons.append("comments")
    if generated:
        reasons.append("generated")
    if minified:
        reasons.append("minified")
    if language == "python" and cfg.require_python_parse and not python_parses(text):
        reasons.append("python_syntax")
    return {
        "language": language,
        "lines": len(nonempty),
        "avg_line_len": round(avg, 2),
        "max_line_len": max_len,
        "alnum_ratio": round(alnum, 4),
        "digit_ratio": round(digits, 4),
        "comment_ratio": round(comments, 4),
        "keep": len(reasons) == 0,
        "drop_reasons": reasons,
    }
